#!/bin/bash

set -e

if [ "$UID" != 0 ]; then
    echo "Error: must run this script as root (e.g. with sudo)" >&2
    exit 1
fi

if [ "$#" != 1 ] || [[ "$1" == -* ]]; then
    echo "Error: usage: $0 https://url/for/mainnet/data.mdb"
    exit 1
fi

if ! [ -e /var/lib/loki ]; then
    echo "/var/lib/loki does not exist; did you properly install the lokid package?"
    exit 1
fi

if ! [ -e /var/lib/loki/lmdb ]; then
    mkdir /var/lib/loki/lmdb
    chown _loki:_loki /var/lib/loki/lmdb
fi

node_active=
ss_active=
if systemctl -q is-active loki-node.service; then node_active=y; fi
if systemctl -q is-active loki-storage-server.service; then ss_active=y; fi

echo "Ready to download lmdb from $1."
if [ -e /var/lib/loki/lmdb/data.mdb ]; then
    echo "Will overwrite existing data.mdb:"
    ls -l --si /var/lib/loki/lmdb/data.mdb
fi
if [ -n "$node_active" ]; then
    echo -n "loki-node.service"
    if [ -n "$ss_active" ]; then echo -n " and loki-storage-server.service"; fi
    echo " will be stopped, then restarted when the lmdb download is complete"
else
    echo "loki-node.service is not currently running and will be left stopped.  (Do not attempt to start it or the storage server until the download is complete!)"
fi

echo

read -p "Press enter to continue, ^C to abort"

if [ -n "$node_active" ]; then
    if [ -n "$ss_active" ]; then
        systemctl stop loki-node.service loki-storage-server.service
    else
        systemctl stop loki-node.service
    fi
fi

curl "$1" >/var/lib/loki/lmdb/data.mdb

chown _loki:_loki /var/lib/loki/lmdb/data.mdb
echo "Downloaded data.mdb:"
ls -l --si /var/lib/loki/lmdb/data.mdb

if [ -n "$node_active" ]; then
    if [ -n "$ss_active" ]; then
        echo "Starting loki-node.service, loki-storage-server.service"
        systemctl start loki-node.service loki-storage-server.service
    else
        echo "Starting loki-node.service"
        systemctl start loki-node.service
    fi
fi
