name: gyuanx
version: 8.1.4
base: core18
summary: "Gyuanx: the secure, private, untraceable cryptocurrency https://gyuan.online"
description: |
    Gyuanx gives a better privacy and makes user to gain complete anonymity during blockchain transactions.
    Gyuanx uses cryptography to shield sending and receiving addresses, as well as transacted amounts.
grade: devel
confinement: strict

apps:
    gyuanxd:
        daemon: forking
        command: |
          gyuanxd-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/gyuanxd.conf
        plugs:
            - network
            - network-bind
    gyuanx-wallet-rpc:
        command: |
          gyuanx-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    gyuanx-wallet-cli:
        command: |
          gyuanx-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DBUILD_STATIC_DEPS=ON
            - -DSTATIC=ON
            - -DCMAKE_C_COMPILER=gcc-8
            - -DCMAKE_CXX_COMPILER=g++-8
            - -DARCH=x86-64
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc-8
            - pkg-config
            - libsystemd-dev
            - libboost-thread-dev
            - libgtest-dev
            - libboost-serialization-dev
            - libboost-program-options-dev
            - libunbound-dev
            - libevent-dev
            - libminiupnpc-dev
            - libunwind8-dev
            - libsodium-dev
            - libssl-dev
            - libreadline-dev
            - libhidapi-dev
            - libusb-1.0-0-dev
            - python3
            - libsqlite3-dev
            - qttools5-dev
            - libcurl4-openssl-dev
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
            - liblzma5 
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/gyuanxd.conf: etc/gyuanxd.conf
            contrib/snap/gyuanxd-wrapper: bin/gyuanxd-wrapper
        prime:
            - etc
            - bin
